#!/bin/sh

echo ${RM_fqdn} > /etc/HOSTNAME
echo "SX_GATEWAY=${RM_gateway}" > /etc/NETCONFIG
echo "SX_NAMESERVER1=${RM_ns1}" >> /etc/NETCONFIG
echo "SX_NAMESERVER2=${RM_ns2}" >> /etc/NETCONFIG

#
# make /etc/resolv.conf
#
echo -n "" > /etc/resolv.conf
if [ ! "${RM_ns1}" = "" ]; then
	echo "nameserver ${RM_ns1}" >> /etc/resolv.conf
fi
if [ ! "${RM_ns2}" = "" ]; then
	echo "nameserver ${RM_ns2}" >> /etc/resolv.conf
fi

cat <<EOF >> /etc/resolv.conf
search `echo ${RM_fqdn} | cut -d. -f 2-`
EOF

#
# make /etc/hosts, if it doesn't exist.
#
etchostsexist=yes
if [ ! -e /etc/hosts ]; then
	etchostsexist=no
	cat <<EOF > /etc/hosts
#
# hosts		This file describes a number of hostname-to-address
#		mappings for the TCP/IP subsystem.  It is mostly
#		used at boot time, when no name servers are running.
#		On small systems, this file can be used instead of a
#		"named" name server.  Just add the names, addresses
#		and any aliases to this file...
#
# By the way, Arnt Gulbrandsen <agulbra@nvg.unit.no> says that 127.0.0.1
# should NEVER be named with the name of the machine.  It causes problems
# for some (stupid) programs, irc and reputedly talk. :^)
#

# For loopbacking.
127.0.0.1	localhost
EOF
fi

printenv | grep RM_if_ | while read LINE
do
    VAR=`echo $LINE | cut -d= -f1`

    ETH=`echo $VAR | cut -d_ -f3`
    TYPE=`echo $VAR | cut -d_ -f4`

    if [ "$TYPE" = "ip" ]; then
	echo SX_NETDEV_${ETH}_IP=`printenv $VAR` >> /etc/NETCONFIG
	if [ "$etchostsexist" = "no" ]; then
    	    if ! echo $(printenv $VAR) | grep -i '^dhcp$' ; then
		REPLY=`printenv $VAR`
		if [ ! "$REPLY" = "" ]; then
		    echo "${REPLY}	${RM_fqdn} `echo ${RM_fqdn} | cut -d. -f1`" >> /etc/hosts
		fi
	    fi
	fi
    elif [ "$TYPE" = "netmask" ]; then
	echo SX_NETDEV_${ETH}_NETMASK=`printenv $VAR` >> /etc/NETCONFIG
    fi
done

