PKG=bandwidthd

include ../sxarchconfig
include sxconfig

$(PKG): install

compile:
	@echo "sorry, no \"compile\", try \"make\" or \"make install\" instead."

install:
	./install.sh

clean:
	./clean.sh

version:
	@echo $(PKG)-$(VERSION)-$(SXARCH)-$(BUILD)
