#!/bin/sh

CWD=`pwd`
sdir="$CWD/../specials"

sh clean
if [ ! -e uclibc ]; then
	sh build.uclibc
fi
sh build.installscript &&
sh build.replimenu &&
sh build.e2fsprogs &&
sh build.ftp &&
sh build.grep &&
sh build.raidtools &&
sh build.shutils &&
sh build.util-linux &&
sh build.eject &&
sh build.hdparm &&
sh build.sysklogd &&
sh build.modutils &&
sh build.dhcpcd &&
sh build.openmosix-tools &&
( strip $sdir/bin/* $sdir/sbin/* $sdir/usr/bin/* $sdir/usr/sbin/*
  sh build.busybox )
if [ ! $? -eq 0 ]; then
	echo
	echo "An error occured, compilation aborted"!
	exit 1
fi
