#!/bin/sh

CWD=`pwd`

source sxconfig || exit 1

if [ "$SRC" = "" ]; then
    echo "SRC variable is fubar!"
    exit 1
fi


for i in *
do
    if [ -d $i ]; then

	cd $i

	if [ -f version.sh ]; then
	    cvs rm -f version.sh
	fi

	cd ..

    fi
done

